version: "3"

tasks:
  update-readme:
    cmds:
      - |
        help_command="gcode-thumbnail-tool"
        help_output=$($help_command)

        extract_command="gcode-thumbnail-tool extract --help"
        extract_output=$($extract_command)

        analyse_command="gcode-thumbnail-tool analyse --help"
        analyse_output=$($analyse_command)

        example_command="gcode-thumbnail-tool analyse tests/_files/prusa_2.9.3.gcode"
        example_output=$($example_command)

        awk -i inplace -v command="$help_command" -v output="$help_output" '
          BEGIN{p=1}
          $1=="<!--INSERT:help-->"{p=0;print;next}
          $1=="<!--/INSERT:help-->"{print "```\n$ " command "\n" output "\n```"; p=1}
          p
        ' README.md
        awk -i inplace -v command="$extract_command" -v output="$extract_output" '
          BEGIN{p=1}
          $1=="<!--INSERT:extract-->"{p=0;print;next}
          $1=="<!--/INSERT:extract-->"{print "```\n$ " command "\n" output "\n```"; p=1}
          p
        ' README.md
        awk -i inplace -v command="$analyse_command" -v output="$analyse_output" '
          BEGIN{p=1}
          $1=="<!--INSERT:analyse-->"{p=0;print;next}
          $1=="<!--/INSERT:analyse-->"{print "```\n$ " command "\n" output "\n```"; p=1}
          p
        ' README.md

        awk -i inplace -v command="$example_command" -v output="$example_output" '
          BEGIN{p=1}
          $1=="<!--INSERT:example-->"{p=0;print;next}
          $1=="<!--/INSERT:example-->"{print "```\n$ " command "\n" output "\n```"; p=1}
          p
        ' README.md
